name: Bernhard Benke – Web Developer
markdown: redcarpet
highlighter: pygments

#ignore files
exclude: [Gemfile, Gemfile.lock, README.md, config.rb, node_modules, package.json, gruntfile.js]

sass:
  sass_dir: 